name: Rust Auto Builder

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@nightly

      - name: Build release
        run: cargo build --release

      - uses: actions/upload-artifact@v5
        with:
          name: release-build
          path: target/release/fluffy_injector.exe
